#!/bin/sh
set -e

find_root() {
   local topd
   if [ -z "${CLOUD_INIT_TOP_D}" ]; then
      topd=$(cd "$(dirname "${0}")" && cd .. && pwd)
   else
      topd=$(cd "${CLOUD_INIT_TOP_D}" && pwd)
   fi
   [ $? -eq 0 -a -f "${topd}/setup.py" ] || return
   ROOT_DIR="$topd"
}

if ! find_root; then
    echo "Unable to locate 'setup.py' file that should" \
          "exist in the cloud-init root directory." 1>&2
    exit 1;
fi

REVNO=$(bzr revno "$ROOT_DIR" || git rev-parse --short HEAD)

if [ ! -z "$1" ]; then
    ARCHIVE_FN="$1"
else
    VERSION=$("$ROOT_DIR/tools/read-version")
    ARCHIVE_FN="$PWD/cloud-init-$VERSION~rightscale1.tar.gz"
fi

bzr export --format=tgz --root="cloud-init-$VERSION~rightscale1" \
    "--revision=${REVNO}" "${ARCHIVE_FN}" "$ROOT_DIR" || git archive \
    --prefix="cloud-init-$VERSION~rightscale1/" HEAD  | gzip > $ARCHIVE_FN

echo "$ARCHIVE_FN"
